### PR TITLE
Fix router.router deprecation warnings

### LINKED ISSUE #657: `router` usage is deprecated
[This line](https://github.com/emberjs/ember-inspector/blob/268503b5dd724bcb4991b907869ec152ae28236a/ember_debug/route-debug.js#L46) causes the following deprecation warning on Ember v2.13.0:

> ember.debug.js:7752 DEPRECATION: Usage of `router` is deprecated, use `_routerMicrolib` instead. [deprecation id: ember-router.router] See http://emberjs.com/deprecations/v2.x/#toc_ember-router-router-renamed-to-ember-router-_routerMicrolib for more details.

I'll send a PR shortly because it's apparently just a simple rename: https://emberjs.com/deprecations/v2.x/#toc_ember-router-router-renamed-to-ember-router-_routermicrolib

### PR DESCRIPTION
**Pull request by bgentry**
Fixes #657.

### CODE REVIEW

File: ember_debug/object-inspector.js [hunk 1]
```diff
@@ -152,7 +152,7 @@ export default EmberObject.extend(PortMixin, {
     },
     inspectRoute(message) {
       const container = this.get('application.__container__');
-      this.sendObject(container.lookup('router:main').router.getHandler(message.name));
+      this.sendObject(container.lookup('router:main')._routerMicrolib.getHandler(message.name));
```
Comment (rwjblue) [inline ember_debug/object-inspector.js]: I think we need to support both (e.g. we need to detect and fallback):

```js
const router = container.lookup('router:main');
const routerMicrolib = router._routerMicrolib || router.router;
this.sendObject(routerMicrolib.getHandler(message.name));
```

Comment (bgentry) [inline ember_debug/object-inspector.js]: d'oh, makes sense. Will tweak it

**Comment by bgentry** [comment]
@rwjblue changes made, lmk if that's what you had in mind.

**Comment by TimvdEijnden** [comment]
Looking forward for this fix but one test failed 😿 
```
not ok 183 PhantomJS 2.1 - Route Tree Debug: Route tree
    ---
        actual: >
            null
        stack: >
            http://localhost:7357/ember_debug.js:4241:37
            get@http://localhost:7357/assets/vendor.js:25398:32
            get@http://localhost:7357/assets/vendor.js:31050:22
            get@http://localhost:7357/assets/vendor.js:45426:41
            sendTree@http://localhost:7357/ember_debug.js:4255:31
            getTree@http://localhost:7357/ember_debug.js:4223:22
            sendEvent@http://localhost:7357/assets/vendor.js:27064:23
            trigger@http://localhost:7357/assets/vendor.js:44718:34
            run@http://localhost:7357/assets/vendor.js:11110:30
            run@http://localhost:7357/assets/vendor.js:31387:32
            t$@http://localhost:7357/assets/tests.js:5157:14
            tryCatch@http://localhost:7357/assets/vendor.js:8:62186
            invoke@http://localhost:7357/assets/vendor.js:9:2907
            http://localhost:7357/assets/vendor.js:9:103
            invoke@http://localhost:7357/assets/vendor.js:9:631
            invoke@[native code]
            http://localhost:7357/assets/vendor.js:8:16400
            http://localhost:7357/assets/vendor.js:8:16604
            exports@http://localhost:7357/assets/vendor.js:6:12887
            http://localhost:7357/assets/vendor.js:6:43431
            run@http://localhost:7357/assets/vendor.js:6:21874
            listner@http://localhost:7357/assets/vendor.js:6:43247
        message: >
            Promise rejected during Route tree: undefined is not a function (evaluating 'routerLib.get('recognizer.names')')
        Log: |```

**Comment by sukima** [comment]
OMG, I don't believe it. I just spent an hour trying to figure out where this was coming from only t find out it the ember-inspector browser extension! I thought my app was all out of whack and my addons were bad addons. I wish there was a way to tell the difference between errors and warnings produced by non-app related code and those your code actually produces.

This totally bit me.

File: ember_debug/route-debug.js [hunk 2]
```diff
@@ -43,7 +43,9 @@ export default EmberObject.extend(PortMixin, {
   }),
 
   routeTree: computed('router', function() {
-    let routeNames = this.get('router.router.recognizer.names');
+    const router = this.get('router');
+    const routerLib = router._routerMicrolib || router.router;
+    let routeNames = routerLib.get('recognizer.names');
```
Comment (rwjblue) [inline ember_debug/route-debug.js]: @bgentry - The remaining CI failure is from this change.  `routerLib.get` is not a function, but since it is not relying on Ember's object model (e.g. no CP's) we can just do `routerLib.recognizer.names` directly.

**Comment by bgentry** [comment]
@rwjblue made the change you requested, lmk if it's sufficient :v:
