### PR TITLE
Prevent errors when document.documentElement.dataset is not present.

### LINKED ISSUE #463: Getting error in console when using Ember Inspector: Uncaught TypeError: Cannot set property 'emberExtension' of undefined
Stacktrace:

Uncaught TypeError: Cannot set property 'emberExtension' of undefined
(anonymous function) @ content-script.js:29
(anonymous function) @ content-script.js:64

The line 29 is as follows:
document.documentElement.dataset.emberExtension = 1;

While pausing at the error using Chrome debugger,
document.documentElement is 
&lt;svg xmlns="http://www.w3.org/2000/svg" version="1.1" id="Layer_1" x="0px" y="0px" width="139.978px" height="10.32px" viewBox="0 0 139.978 10.32" enable-background="accumulate" xml:space="preserve"&gt;...&lt;/svg&gt;

and document.documentElement.dataset is undefined

### PR DESCRIPTION
**Pull request by rwjblue**
If `document.documentElement` does not have a `dataset` property we will never mark the content script as loaded (and it cannot be an Ember app) this happens in some scenarios with Chrome 45+ and SVG elements.

Fixes #463
Closes #473

### CODE REVIEW

**Comment by rwjblue** [comment]
@teddyzeenny - Should be ready for review...

File: ember_debug/adapters/basic.js [hunk 1]
```diff
@@ -117,7 +117,15 @@ export default EmberObject.extend({
...
         this.interval = setInterval(() => {
-          if (document.documentElement.dataset.emberExtension) {
+          if (
+            // if `document.documentElement` does not have a `dataset` property we
+            // will never mark the content script as loaded (and it cannot be an Ember app)
+            // this happens in some scenarios with Chrome 45+ and SVG elements.
+            (document.documentElement && !document.documentElement.dataset) ||
+
+              // when the content script is loaded, this flag is set to `1`
+              document.documentElement.dataset.emberExtensions
```
Comment (teddyzeenny) [inline ember_debug/adapters/basic.js]: This code wouldn't execute if it's not an Ember app.

File: skeleton_chrome/content-script.js [hunk 2]
```diff
@@ -25,8 +25,13 @@
     port.start();
   }
 
-  // let ember-debug know that content script has executed
-  document.documentElement.dataset.emberExtension = 1;
+  // document.documentElement.dataset is not present for SVG elements
+  // this guard (and a corresponding one in ember-debug/adapters/basic)
+  // prevents that condition from triggering an error
+  if (document.documentElement && document.documentElement.dataset) {
```
Comment (teddyzeenny) [inline skeleton_chrome/content-script.js]: :+1:

File: ember_debug/adapters/basic.js (hunk 1 above)
Comment (rwjblue) [inline ember_debug/adapters/basic.js]: Ok, so you are saying that we do not need to guard here?

Comment (teddyzeenny) [inline ember_debug/adapters/basic.js]: Confirm

Comment (rwjblue) [inline ember_debug/adapters/basic.js]: Updated

File: skeleton_chrome/content-script.js [hunk 3]
```diff
@@ -25,8 +25,13 @@
     port.start();
   }
 
-  // let ember-debug know that content script has executed
-  document.documentElement.dataset.emberExtension = 1;
+  // document.documentElement.dataset is not present for SVG elements
+  // this guard (and a corresponding one in ember-debug/adapters/basic)
```
Comment (teddyzeenny) [inline skeleton_chrome/content-script.js]: can you update the comment?

Comment (rwjblue) [inline skeleton_chrome/content-script.js]: Updated

**Comment by teddyzeenny** [comment]
Thank you!!
